{
 "title": "Node",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Systemd state",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(state) (node_systemd_unit_state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Network activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node\"}[5m])",
     "legendFormat": "{{device}} (receive)"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node\"}[5m])",
     "legendFormat": "{{device}} (send)"
    }
   ]
  },
  {
   "title": "Domain expiry time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "targets": [
    { "expr": "domain_expiry_days", "legendFormat": "{{domain}}" }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{job=\"node\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Nginx HTTP requests/5min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Free disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes / node_filesystem_size_bytes{job=\"node\"}",
     "legendFormat": "{{mountpoint}} ({{device}})"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{mode!=\"idle\"}[5m])",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "type": "welcome",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Dashboards",
   "type": "dashlist",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Latest from the blog",
   "type": "news",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {}
   ]
  }
 ]
}