keys:
  - &patrick "age1uswp3m453z9vuvqcxcu5a7pnyu7l3vc09q6j99jywc08kag2r30qxk6254"
  - &staging_server 'age1kwfcmu2uh5hanqpes9gv27n3aydlrj7t6u48n6k4ylu2wycdmq8qk688p8'
creation_rules:
  - path_regex: "secrets/[^/]+\\.json$"
    key_groups:
    - age:
      - *staging_server
      - *patrick
