# docker-compose.yml
version: '3'

services:
    woodpecker-server:
        image: woodpeckerci/woodpecker-server:next
        ports: ["%%WOODPECKER_PORT%%:8000"]
        volumes:
            - woodpecker-server-data:/var/lib/woodpecker
        environment:
            - WOODPECKER_OPEN=true
            - WOODPECKER_HOST=https://%%WOODPECKER_SUBDOMAIN%%.%%WOODPECKER_DOMAIN%%
            - WOODPECKER_GITEA=true
            - WOODPECKER_GITEA_URL=https://%%GITEA_SUBDOMAIN%%.%%WOODPECKER_DOMAIN%%
            - WOODPECKER_GITEA_CLIENT=${WOODPECKER_GITEA_CLIENT_OAUTH_ID}
            - WOODPECKER_GITEA_SECRET=${WOODPECKER_GITEA_SECRET}
            - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}

    woodpecker-agent:
        image: woodpeckerci/woodpecker-agent:next
        command: agent
        restart: always
        depends_on: [woodpecker-server]
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - WOODPECKER_SERVER=woodpecker-server:9000
            - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}

volumes:
    woodpecker-server-data:
